language: node_js
node_js:
  - '11'
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: false
  on:
    branch: master
before_script:
  - 'npm i -g gatsby'
script:
  - 'npm run predeploy'
